### ISSUE TITLE
Failed HTML markup validation for index.html. 

### ISSUE THREAD

**Issue by abatomunkuev** [rclee91/SiteGen#2]
I have tested the HTML files in [Validator](https://html5.validator.nu/). I tried to input a folder to generate multiple files + index.html. Generated pages from processed text files were valid. However, the index.html failed markup validation. Please consider reviewing the image below. 

<img width="1680" alt="Screen Shot 2021-09-17 at 4 46 50 PM" src="https://user-images.githubusercontent.com/55283735/133852167-f5b768a0-a834-4afb-b765-3fb83585bbb3.png">

**Comment by rclee91** [comment]
Updated all .html file links and file names to replace space with "_" in compliance of markup validation.

Thank you!
