### ISSUE TITLE
Add more validaiton on reading file extensions.

### ISSUE THREAD

**Issue by abatomunkuev** [rclee91/SiteGen#3]
I have duplicated the file "Silver Blaze.txt", and added additional extension. "Silver Blaze.txt.t". The tool still has processed the file. I think that the tool is needed more validation.
<img width="597" alt="Screen Shot 2021-09-17 at 5 12 14 PM" src="https://user-images.githubusercontent.com/55283735/133854306-c8e45b53-854f-4711-b589-ba16a824bd82.png">

<img width="328" alt="Screen Shot 2021-09-17 at 5 14 13 PM" src="https://user-images.githubusercontent.com/55283735/133854325-e433c1ee-f459-43a1-8269-e317d2a01f06.png">

**Comment by rclee91** [comment]
Updated validation of files ending with .txt instead of searching for files with ".txt" in their name. 
This should solve the file extension validation issue.

Thank you!
